sonar.projectKey=SONAR_TOKEN
sonar.organization=b02a9014929c9a6ee2d1098e74b2e6ae7fd64ff9
sonar.sources=src,supabase/functions
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.app.json,tsconfig.node.json

sonar.sourceEncoding=UTF-8